#
# makefile
# Tim Green
# 3/20/14
# version 1.0
#
# Project 3 - Matrix Multiplication, Producer-Consumer
#
# NOTE: remove -g from CFLAGS to disable debugging information in executable

CC = gcc-4.7
CFLAGS = -Wall -Wextra -g -lpthread

matrix.x : matrix.c
	$(CC) $(CFLAGS) matrix.c -o matrix.x
