#
# makefile
# Tim Green
# 1/25/14
# version 1.0
#
# Project 1 - UNIX Shell
#
# NOTE: remove -g from CFLAGS to disable debugging information in executable

CC = gcc-4.7
CFLAGS = -Wall -Wextra -g

myshell.x : myshell.c
	$(CC) $(CFLAGS) myshell.c -o myshell.x
